export const usersData = [
  {
    name: "Mariah Chan",
    email: "mariahchan@gmail.com",
    mobile: "+441234567891",
    query: "consumer",
    rsvp: true,
    staff: "Mariana",
  },
  {
    name: "Mark Wilson",
    email: "markwilson@gmail.com",
    mobile: "+441234567892",
    query: "consultant",
    rsvp: false,
    staff: "Oliver",
  },
  {
    name: "Lila Patel",
    email: "lilapatel@gmail.com",
    mobile: "+441234567893",
    query: "consumer",
    rsvp: true,
    staff: "Anthony",
  },
  {
    name: "Ashley Williams",
    email: "ashleywilliams@gmail.com",
    mobile: "+441234567894",
    query: "consultant",
    rsvp: true,
    staff: "Nikhil",
  },
  {
    name: "John Lee",
    email: "johnlee@gmail.com",
    mobile: "+441234567895",
    query: "consumer",
    rsvp: false,
    staff: "Jessica",
  },
  {
    name: "Karen Chen",
    email: "karenchen@gmail.com",
    mobile: "+441234567896",
    query: "consumer",
    rsvp: true,
    staff: "Oliver",
  },
  {
    name: "Sean Baker",
    email: "seanbaker@gmail.com",
    mobile: "+441234567897",
    query: "consultant",
    rsvp: false,
    staff: "Mariana",
  },
  {
    name: "Sophie Kim",
    email: "sophiekim@gmail.com",
    mobile: "+441234567898",
    query: "consumer",
    rsvp: true,
    staff: "Jessica",
  },
  {
    name: "Adam Johnson",
    email: "adamjohnson@gmail.com",
    mobile: "+441234567899",
    query: "consultant",
    rsvp: true,
    staff: "Anthony",
  },
  {
    name: "Ethan Chen",
    email: "ethanchen@gmail.com",
    mobile: "+441234567900",
    query: "consumer",
    rsvp: false,
    staff: "Nikhil",
  },
  {
    name: "Melanie Wong",
    email: "melaniewong@gmail.com",
    mobile: "+441234567901",
    query: "consumer",
    rsvp: true,
    staff: "Jessica",
  },
  {
    name: "Peter Brown",
    email: "peterbrown@gmail.com",
    mobile: "+441234567902",
    query: "consultant",
    rsvp: false,
    staff: "Oliver",
  },
  {
    name: "Jasmine Wang",
    email: "jasminewang@gmail.com",
    mobile: "+441234567903",
    query: "consumer",
    rsvp: true,
    staff: "Mariana",
  },
  {
    name: "David Chen",
    email: "davidchen@gmail.com",
    mobile: "+441234567904",
    query: "consumer",
    rsvp: true,
    staff: "Anthony",
  },
  {
    name: "Alice Lee",
    email: "alicelee@gmail.com",
    mobile: "+441234567905",
    query: "consultant",
    rsvp: false,
    staff: "Nikhil",
  },
  {
    name: "Rachel Kim",
    email: "rachelkim@gmail.com",
    mobile: "+441234567906",
    query: "consumer",
    rsvp: true,
    staff: "Jessica",
  },
  {
    name: "Alex Nguyen",
    email: "alexnguyen@gmail.com",
    mobile: "+441234567907",
    query: "consultant",
    rsvp: true,
    staff: "Oliver",
  },
  {
    name: "Emily Brown",
    email: "emilybrown@gmail.com",
    mobile: "+441234567908",
    query: "consumer",
    rsvp: false,
    staff: "Mariana",
  },
  {
    name: "Jason Lee",
    email: "jasonlee@gmail.com",
    mobile: "+441234567909",
    query: "consumer",
    rsvp: true,
    staff: "Jessica",
  },
  {
    name: "Erica Chen",
    email: "ericachen@gmail.com",
    mobile: "+441234567910",
    query: "consultant",
    rsvp: false,
    staff: "Nikhil",
  },
  {
    name: "Bryan Kim",
    email: "bryankim@gmail.com",
    mobile: "+441234567911",
    query: "consumer",
    rsvp: true,
    staff: "Anthony",
  },
  {
    name: "Chloe Wong",
    email: "chloewong@gmail.com",
    mobile: "+441234567912",
    query: "consumer",
    rsvp: false,
    staff: "Oliver",
  },
  {
    name: "Daniel Lee",
    email: "daniellee@gmail.com",
    mobile: "+441234567913",
    query: "consultant",
    rsvp: true,
    staff: "Mariana",
  },
  {
    name: "Grace Park",
    email: "gracepark@gmail.com",
    mobile: "+441234567914",
    query: "consumer",
    rsvp: true,
    staff: "Jessica",
  },
  {
    name: "Isabella Kim",
    email: "isabellakim@gmail.com",
    mobile: "+441234567916",
    query: "consumer",
    rsvp: true,
    staff: "Anthony",
  },
  {
    name: "Jack Wang",
    email: "jackwang@gmail.com",
    mobile: "+441234567917",
    query: "consultant",
    rsvp: true,
    staff: "Oliver",
  },
  {
    name: "Katherine Lee",
    email: "katherinelee@gmail.com",
    mobile: "+441234567918",
    query: "consumer",
    rsvp: false,
    staff: "Mariana",
  },
  {
    name: "Luke Chen",
    email: "lukechen@gmail.com",
    mobile: "+441234567919",
    query: "consumer",
    rsvp: true,
    staff: "Jessica",
  },
  {
    name: "Megan Kim",
    email: "megankim@gmail.com",
    mobile: "+441234567920",
    query: "consultant",
    rsvp: false,
    staff: "Nikhil",
  },
  {
    name: "Nathan Wong",
    email: "nathanwong@gmail.com",
    mobile: "+441234567921",
    query: "consumer",
    rsvp: true,
    staff: "Anthony",
  },
  {
    name: "Olivia Lee",
    email: "olivialeexx@gmail.com",
    mobile: "+441234567922",
    query: "consumer",
    rsvp: false,
    staff: "Oliver",
  },
  {
    name: "Patrick Park",
    email: "patrickpark@gmail.com",
    mobile: "+441234567923",
    query: "consultant",
    rsvp: true,
    staff: "Mariana",
  },
  {
    name: "Rachel Wang",
    email: "rachelwang@gmail.com",
    mobile: "+441234567924",
    query: "consumer",
    rsvp: true,
    staff: "Jessica",
  },
  {
    name: "Henry Nguyen",
    email: "henrynguyen@gmail.com",
    mobile: "+441234567915",
    query: "consultant",
    rsvp: false,
    staff: "Nikhil",
  },
];

export const resourceData = [
  {
    resourceName: "Syringes",
    quantity: 580,
    cost: "£25.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 300,
  },
  {
    resourceName: "Dental Mirrors",
    quantity: 200,
    cost: "£2.50",
    isAutoPurchase: false,
    autoPurchaseLevel: 0,
  },
  {
    resourceName: "Handpieces",
    quantity: 900,
    cost: "£75.00",
    isAutoPurchase: true,
    autoPurchaseLevel: 800,
  },
  {
    resourceName: "Scalers",
    quantity: 250,
    cost: "£12.99",
    isAutoPurchase: false,
    autoPurchaseLevel: 0,
  },
  {
    resourceName: "Forceps",
    quantity: 400,
    cost: "£32.50",
    isAutoPurchase: true,
    autoPurchaseLevel: 350,
  },
  {
    resourceName: "Surgical Burs",
    quantity: 750,
    cost: "£50.00",
    isAutoPurchase: false,
    autoPurchaseLevel: 0,
  },
  {
    resourceName: "Anesthetic Needles",
    quantity: 150,
    cost: "£8.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 100,
  },
  {
    resourceName: "Retractors",
    quantity: 350,
    cost: "£15.50",
    isAutoPurchase: false,
    autoPurchaseLevel: 0,
  },
  {
    resourceName: "Matrix Bands",
    quantity: 550,
    cost: "£5.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 400,
  },
  {
    resourceName: "Composite Instruments",
    quantity: 400,
    cost: "£42.50",
    isAutoPurchase: false,
    autoPurchaseLevel: 0,
  },
  {
    resourceName: "Prophy Paste",
    quantity: 650,
    cost: "£22.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 500,
  },
  {
    resourceName: "Alginate Impression Material",
    quantity: 200,
    cost: "£75.00",
    isAutoPurchase: false,
    autoPurchaseLevel: 0,
  },
  {
    resourceName: "Cotton Rolls",
    quantity: 750,
    cost: "£1.50",
    isAutoPurchase: true,
    autoPurchaseLevel: 600,
  },
  {
    resourceName: "Gloves",
    quantity: 400,
    cost: "£10.99",
    isAutoPurchase: false,
    autoPurchaseLevel: 0,
  },
  {
    resourceName: "Saliva Ejectors",
    quantity: 300,
    cost: "£0.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 200,
  },
  {
    resourceName: "Dental X-Ray Machine",
    quantity: 2,
    cost: "£3,999.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 150,
  },
  {
    resourceName: "Ultrasonic Scaler",
    quantity: 15,
    cost: "£299.99",
    isAutoPurchase: false,
    autoPurchaseLevel: 70,
  },
  {
    resourceName: "Dental Loupes",
    quantity: 30,
    cost: "£99.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 120,
  },
  {
    resourceName: "Air Compressor",
    quantity: 5,
    cost: "£799.99",
    isAutoPurchase: false,
    autoPurchaseLevel: 50,
  },
  {
    resourceName: "Dental Handpiece",
    quantity: 25,
    cost: "£149.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 90,
  },
  {
    resourceName: "Dental Implant Kit",
    quantity: 2,
    cost: "£1,999.99",
    isAutoPurchase: false,
    autoPurchaseLevel: 30,
  },
  {
    resourceName: "Curing Light",
    quantity: 20,
    cost: "£79.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 80,
  },
  {
    resourceName: "Dental Hand Instruments Set",
    quantity: 10,
    cost: "£399.99",
    isAutoPurchase: false,
    autoPurchaseLevel: 60,
  },
  {
    resourceName: "Intraoral Camera",
    quantity: 8,
    cost: "£299.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 100,
  },
  {
    resourceName: "Dental Impression Kit",
    quantity: 12,
    cost: "£149.99",
    isAutoPurchase: false,
    autoPurchaseLevel: 40,
  },
  {
    resourceName: "Dental X-Ray Film",
    quantity: 200,
    cost: "£29.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 250,
  },
  {
    resourceName: "Dental Air Abrasion System",
    quantity: 4,
    cost: "£1,299.99",
    isAutoPurchase: false,
    autoPurchaseLevel: 20,
  },
  {
    resourceName: "Digital Impression Scanner",
    quantity: 3,
    cost: "£5,999.99",
    isAutoPurchase: true,
    autoPurchaseLevel: 200,
  },
  {
    resourceName: "Dental Surgery Light",
    quantity: 5,
    cost: "£499.99",
    isAutoPurchase: false,
    autoPurchaseLevel: 50,
  },
];

export const bookingData = [
  {
    name: "Megan Kim",
    email: "megankim@gmail.com",
    mobile: "+441234567920",
    bookingDate: "12/03/2023",
    bookingTime: "12:30",
    cost: "£12.99",
  },
  {
    name: "Mark Wilson",
    email: "markwilson@gmail.com",
    mobile: "+441234567892",
    bookingDate: "15/03/2023",
    bookingTime: "12:30",
    cost: "£150",
  },
  {
    name: "Ethan Carter",
    email: "ethancarter@gmail.com",
    mobile: "+441234567897",
    bookingDate: "07/04/2023",
    bookingTime: "10:30",
    cost: "£250",
  },
  {
    name: "Jasmine Patel",
    email: "jasminepatel@gmail.com",
    mobile: "+441234567904",
    bookingDate: "18/04/2023",
    bookingTime: "14:00",
    cost: "£85",
  },
  {
    name: "Derek Lee",
    email: "dereklee@gmail.com",
    mobile: "+441234567912",
    bookingDate: "22/05/2023",
    bookingTime: "16:00",
    cost: "£350",
  },
  {
    name: "Samantha Jones",
    email: "samanthajones@gmail.com",
    mobile: "+441234567922",
    bookingDate: "05/06/2023",
    bookingTime: "11:30",
    cost: "£40",
  },
  {
    name: "Alexis Brown",
    email: "alexisbrown@gmail.com",
    mobile: "+441234567930",
    bookingDate: "17/06/2023",
    bookingTime: "14:30",
    cost: "£120",
  },
  {
    name: "Michael Davis",
    email: "michaeldavis@gmail.com",
    mobile: "+441234567940",
    bookingDate: "25/07/2023",
    bookingTime: "15:30",
    cost: "£50",
  },
  {
    name: "Sofia Hernandez",
    email: "sofiahernandez@gmail.com",
    mobile: "+441234567951",
    bookingDate: "11/08/2023",
    bookingTime: "16:30",
    cost: "£200",
  },
  {
    name: "Ryan Thompson",
    email: "ryanthompson@gmail.com",
    mobile: "+441234567963",
    bookingDate: "22/08/2023",
    bookingTime: "10:00",
    cost: "£70",
  },
  {
    name: "Maria Rodriguez",
    email: "mariarodriguez@gmail.com",
    mobile: "+441234567975",
    bookingDate: "06/09/2023",
    bookingTime: "12:00",
    cost: "£175",
  },
  {
    name: "Linda Smith",
    email: "lindasmith@gmail.com",
    mobile: "+441234567891",
    bookingDate: "04/05/2023",
    bookingTime: "11:00",
    cost: "£300",
  },
  {
    name: "Jackie Lee",
    email: "jackielee@gmail.com",
    mobile: "+441234567893",
    bookingDate: "22/06/2023",
    bookingTime: "15:30",
    cost: "£250",
  },
  {
    name: "Maria Hernandez",
    email: "mariahernandez@gmail.com",
    mobile: "+441234567894",
    bookingDate: "09/08/2023",
    bookingTime: "10:00",
    cost: "£100",
  },
  {
    name: "Robert Johnson",
    email: "robertjohnson@gmail.com",
    mobile: "+441234567895",
    bookingDate: "15/09/2023",
    bookingTime: "16:00",
    cost: "£75",
  },
  {
    name: "Jenny Nguyen",
    email: "jennynguyen@gmail.com",
    mobile: "+441234567896",
    bookingDate: "11/10/2023",
    bookingTime: "14:00",
    cost: "£180",
  },
  {
    name: "David Brown",
    email: "davidbrown@gmail.com",
    mobile: "+441234567897",
    bookingDate: "08/12/2023",
    bookingTime: "11:30",
    cost: "£50",
  },
  {
    name: "Rachel Kim",
    email: "rachelkim@gmail.com",
    mobile: "+441234567898",
    bookingDate: "16/01/2023",
    bookingTime: "12:00",
    cost: "£20",
  },
  {
    name: "John Davis",
    email: "johndavis@gmail.com",
    mobile: "+441234567899",
    bookingDate: "22/02/2023",
    bookingTime: "10:30",
    cost: "£80",
  },
  {
    name: "Karen Wilson",
    email: "karenwilson@gmail.com",
    mobile: "+4412345678910",
    bookingDate: "18/03/2023",
    bookingTime: "16:30",
    cost: "£200",
  },
];

